In [114]:
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
from flask import Flask, jsonify
from sqlalchemy.engine import url
import json
from sqlalchemy import extract
from sqlalchemy.engine import make_url
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import text
import psycopg2

In [115]:
with open('config_copy.json') as datafile:
    data = json.load(datafile)

env = data['dev']

In [116]:
db = env['db']
user = env['user']
password = env['pass']
port = env['port']
host = env['host']

In [117]:
engine = sqlalchemy.create_engine(f'postgresql://{user}:{password}@{host}:{port}/{db}')

In [118]:
Base = automap_base()

In [119]:
Base.prepare(autoload_with = engine)

In [120]:
Base.classes.keys()

['jhu_cre_cases_deaths', 'location']

In [121]:
location = Base.classes.location

In [122]:
jhu_data = Base.classes.jhu_cre_cases_deaths

In [123]:
Session = sessionmaker(bind = engine)

session = Session()

In [124]:
sql = session.query(jhu_data)

In [125]:
jhucredf = pd.DataFrame(engine.connect().execute(text(str(sql))))

In [126]:
jhucredf

jhu_cre_cases_deaths_fips  jhu_cre_cases_deaths_cases  \
0                          1001                       19732   
1                          1003                       69641   
2                          1005                        7451   
3                          1007                        8067   
4                          1009                       18616   
...                         ...                         ...   
3137                      56037                       12484   
3138                      56039                       12123   
3139                      56041                        6378   
3140                      56043                        2749   
3141                      56045                        1903   

      jhu_cre_cases_deaths_deaths  jhu_cre_cases_deaths_lat  \
0                             230                 32.539527   
1                             724                 30.727750   
2                             103                 31.868263   
3                             109                 32.996421   
4                             261                 33.982109   
...                           ...                       ...   
3137                          139                 41.659439   
3138                           16                 43.935225   
3139                           43                 41.287818   
3140                           50                 43.904516   
3141                           23                 43.839612   

      jhu_cre_cases_deaths_long jhu_cre_cases_deaths_state  \
0                    -86.644082                    Alabama   
1                    -87.722071                    Alabama   
2                    -85.387129                    Alabama   
3                    -87.125115                    Alabama   
4                    -86.567906                    Alabama   
...                         ...                        ...   
3137                -108.882788                    Wyoming   
3138                -110.589080                    Wyoming   
3139                -110.547578                    Wyoming   
3140                -107.680187                    Wyoming   
3141                -104.567488                    Wyoming   

     jhu_cre_cases_deaths_county  jhu_cre_cases_deaths_popuni  \
0                 Autauga County                        55688   
1                 Baldwin County                       221898   
2                 Barbour County                        22023   
3                    Bibb County                        20393   
4                  Blount County                        57697   
...                          ...                          ...   
3137           Sweetwater County                        41888   
3138                Teton County                        23390   
3139                Uinta County                        20183   
3140             Washakie County                         7738   
3141               Weston County                         6664   

      jhu_cre_cases_deaths_total_population  jhu_cre_cases_deaths_zero_rf  \
0                                     55380                         20573   
1                                    212830                         78622   
2                                     25361                          5024   
3                                     22493                          6280   
4                                     57681                         18189   
...                                     ...                           ...   
3137                                  43521                         16977   
3138                                  23280                          7250   
3139                                  20479                          7744   
3140                                   8027                          2601   
3141                                   7049                          1857   

      ...  jhu_cre_cases_deaths_single_fa

In [127]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [128]:
jhucredf.columns

Index(['jhu_cre_cases_deaths_fips', 'jhu_cre_cases_deaths_cases',
       'jhu_cre_cases_deaths_deaths', 'jhu_cre_cases_deaths_lat',
       'jhu_cre_cases_deaths_long', 'jhu_cre_cases_deaths_state',
       'jhu_cre_cases_deaths_county', 'jhu_cre_cases_deaths_popuni',
       'jhu_cre_cases_deaths_total_population', 'jhu_cre_cases_deaths_zero_rf',
       'jhu_cre_cases_deaths_one_two_rf', 'jhu_cre_cases_deaths_three_rf',
       'jhu_cre_cases_deaths_housing_units',
       'jhu_cre_cases_deaths_hispanic_pop', 'jhu_cre_cases_deaths_white_pop',
       'jhu_cre_cases_deaths_black_pop', 'jhu_cre_cases_deaths_native_pop',
       'jhu_cre_cases_deaths_asian_pop',
       'jhu_cre_cases_deaths_pacific_islander_pop',
       'jhu_cre_cases_deaths_other_race_pop',
       'jhu_cre_cases_deaths_bi_tri_racial_pop',
       'jhu_cre_cases_deaths_male_pop', 'jhu_cre_cases_deaths_female_pop',
       'jhu_cre_cases_deaths_veteran', 'jhu_cre_cases_deaths_gini_ind_income',
       'jhu_cre_cases_deaths_rural_po

In [129]:
jhucredf.isnull().sum()

jhu_cre_cases_deaths_fips                      0
jhu_cre_cases_deaths_cases                     0
jhu_cre_cases_deaths_deaths                    0
jhu_cre_cases_deaths_lat                       0
jhu_cre_cases_deaths_long                      0
jhu_cre_cases_deaths_state                     0
jhu_cre_cases_deaths_county                    0
jhu_cre_cases_deaths_popuni                    0
jhu_cre_cases_deaths_total_population          0
jhu_cre_cases_deaths_zero_rf                   0
jhu_cre_cases_deaths_one_two_rf                0
jhu_cre_cases_deaths_three_rf                  0
jhu_cre_cases_deaths_housing_units             0
jhu_cre_cases_deaths_hispanic_pop              0
jhu_cre_cases_deaths_white_pop                 0
jhu_cre_cases_deaths_black_pop                 0
jhu_cre_cases_deaths_native_pop                0
jhu_cre_cases_deaths_asian_pop                 0
jhu_cre_cases_deaths_pacific_islander_pop      0
jhu_cre_cases_deaths_other_race_pop            0
jhu_cre_cases_deaths

In [130]:
jhucredf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 41 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   jhu_cre_cases_deaths_fips                    3142 non-null   int64  
 1   jhu_cre_cases_deaths_cases                   3142 non-null   int64  
 2   jhu_cre_cases_deaths_deaths                  3142 non-null   int64  
 3   jhu_cre_cases_deaths_lat                     3142 non-null   float64
 4   jhu_cre_cases_deaths_long                    3142 non-null   float64
 5   jhu_cre_cases_deaths_state                   3142 non-null   object 
 6   jhu_cre_cases_deaths_county                  3142 non-null   object 
 7   jhu_cre_cases_deaths_popuni                  3142 non-null   int64  
 8   jhu_cre_cases_deaths_total_population        3142 non-null   int64  
 9   jhu_cre_cases_deaths_zero_rf                 3142 non-null   int64  
 10  

In [131]:
jhu_cre = jhucredf.drop(["jhu_cre_cases_deaths_fips", "jhu_cre_cases_deaths_lat", "jhu_cre_cases_deaths_long", "jhu_cre_cases_deaths_state", "jhu_cre_cases_deaths_county" ], axis = 1)
jhu_cre.head()

jhu_cre_cases_deaths_cases  jhu_cre_cases_deaths_deaths  \
0                       19732                          230   
1                       69641                          724   
2                        7451                          103   
3                        8067                          109   
4                       18616                          261   

   jhu_cre_cases_deaths_popuni  jhu_cre_cases_deaths_total_population  \
0                        55688                                  55380   
1                       221898                                 212830   
2                        22023                                  25361   
3                        20393                                  22493   
4                        57697                                  57681   

   jhu_cre_cases_deaths_zero_rf  jhu_cre_cases_deaths_one_two_rf  \
0                         20573                            22750   
1                         78622                            90552   
2                          5024                             9171   
3                          6280                             8986   
4                         18189                            23950   

   jhu_cre_cases_deaths_three_rf  jhu_cre_cases_deaths_housing_units  \
0                          12365                               23493   
1                          52724                              114164   
2                           7828                               12013   
3                           5127                                9185   
4                          15558                               24323   

   jhu_cre_cases_deaths_hispanic_pop  jhu_cre_cases_deaths_white_pop  ...  \
0                               1559                           41543  ...   
1                              10207                          184397  ...   
2                                969                           10086  ...   
3                                530                           15192  ...   
4                               5365                           50138  ...   

   jhu_cre_cases_deaths_single_fathers_pop  \
0                                      723   
1                                     2218   
2                                      220   
3                                      346   
4                                     1038   

   jhu_cre_cases_deaths_plus_family_homes  \
0                                     111   
1                                     887   
2                                     132   
3                                     163   
4                                     115   

   jhu_cre_cases_deaths_highschool_grad  \
0                                 49283   
1                                201483   
2                                 16120   
3                                 16130   
4                                 46446   

   jhu_cre_cases_deaths_multilingual_5yrs_plus  \
0                                          779   
1                                         3994   
2                                          572   
3                                          265   
4                                         1961   

   jhu_cre_cases_deaths_full_time_workers  \
0                                   29291   
1                                  112058   
2                                    8170   
3                                    8096   
4                                   27463   

   jhu_cre_cases_deaths_no_health_insur  jhu_cre_cases_deaths_internet_homes  \
0                                  3953                                44884   
1                                 19748                               181512   
2                                  2488                                13323   
3                                  2182                                14111   
4                                  6231                                42118   

   jhu_cre_cases_deaths_no

In [132]:
# Creating empty column in preparation of for loop
jhu_cre['death_cat'] = ""
jhu_cre.head()

jhu_cre_cases_deaths_cases  jhu_cre_cases_deaths_deaths  \
0                       19732                          230   
1                       69641                          724   
2                        7451                          103   
3                        8067                          109   
4                       18616                          261   

   jhu_cre_cases_deaths_popuni  jhu_cre_cases_deaths_total_population  \
0                        55688                                  55380   
1                       221898                                 212830   
2                        22023                                  25361   
3                        20393                                  22493   
4                        57697                                  57681   

   jhu_cre_cases_deaths_zero_rf  jhu_cre_cases_deaths_one_two_rf  \
0                         20573                            22750   
1                         78622                            90552   
2                          5024                             9171   
3                          6280                             8986   
4                         18189                            23950   

   jhu_cre_cases_deaths_three_rf  jhu_cre_cases_deaths_housing_units  \
0                          12365                               23493   
1                          52724                              114164   
2                           7828                               12013   
3                           5127                                9185   
4                          15558                               24323   

   jhu_cre_cases_deaths_hispanic_pop  jhu_cre_cases_deaths_white_pop  ...  \
0                               1559                           41543  ...   
1                              10207                          184397  ...   
2                                969                           10086  ...   
3                                530                           15192  ...   
4                               5365                           50138  ...   

   jhu_cre_cases_deaths_plus_family_homes  \
0                                     111   
1                                     887   
2                                     132   
3                                     163   
4                                     115   

   jhu_cre_cases_deaths_highschool_grad  \
0                                 49283   
1                                201483   
2                                 16120   
3                                 16130   
4                                 46446   

   jhu_cre_cases_deaths_multilingual_5yrs_plus  \
0                                          779   
1                                         3994   
2                                          572   
3                                          265   
4                                         1961   

   jhu_cre_cases_deaths_full_time_workers  \
0                                   29291   
1                                  112058   
2                                    8170   
3                                    8096   
4                                   27463   

   jhu_cre_cases_deaths_no_health_insur  jhu_cre_cases_deaths_internet_homes  \
0                                  3953                                44884   
1                                 19748                               181512   
2                                  2488                                13323   
3                                  2182                                14111   
4                                  6231                                42118   

   jhu_cre_cases_deaths_no_vehicle  jhu_cre_cases_deaths_homeowner_vacancy  \
0                             2450                                     779   
1                             7322                                    7322   
2                             2246                                   

In [133]:
jhu_cre.describe()

jhu_cre_cases_deaths_cases  jhu_cre_cases_deaths_deaths  \
count                3.142000e+03                   3142.00000   
mean                 3.213884e+04                    349.12317   
std                  1.109969e+05                   1124.50972   
min                  0.000000e+00                      0.00000   
25%                  3.097750e+03                     47.00000   
50%                  7.899000e+03                    110.00000   
75%                  2.120975e+04                    261.00000   
max                  3.691301e+06                  35250.00000   

       jhu_cre_cases_deaths_popuni  jhu_cre_cases_deaths_total_population  \
count                 3.142000e+03                           3.142000e+03   
mean                  1.028667e+05                           1.033411e+05   
std                   3.303224e+05                           3.311701e+05   
min                   8.600000e+01                           6.600000e+01   
25%                   1.070925e+04                           1.095200e+04   
50%                   2.519550e+04                           2.573950e+04   
75%                   6.695000e+04                           6.786600e+04   
max                   9.949102e+06                           1.008157e+07   

       jhu_cre_cases_deaths_zero_rf  jhu_cre_cases_deaths_one_two_rf  \
count                  3.142000e+03                     3.142000e+03   
mean                   3.555582e+04                     4.511753e+04   
std                    1.029070e+05                     1.583837e+05   
min                    2.000000e+01                     3.900000e+01   
25%                    3.045500e+03                     4.517250e+03   
50%                    7.858500e+03                     1.074350e+04   
75%                    2.261150e+04                     2.859225e+04   
max                    2.503900e+06                     5.264628e+06   

       jhu_cre_cases_deaths_three_rf  jhu_cre_cases_deaths_housing_units  \
count                   3.142000e+03                        3.142000e+03   
mean                    2.219337e+04                        4.373933e+04   
std                     7.377844e+04                        1.279317e+05   
min                     2.700000e+01                        6.600000e+01   
25%                     2.867000e+03                        5.505000e+03   
50%                     6.488500e+03                        1.249650e+04   
75%                     1.540625e+04                        3.148100e+04   
max                     2.180574e+06                        3.542800e+06   

       jhu_cre_cases_deaths_hispanic_pop  jhu_cre_cases_deaths_white_pop  ...  \
count                       3.142000e+03                    3.142000e+03  ...   
mean                        1.859688e+04                    6.241113e+04  ...   
std                         1.257639e+05                    1.427950e+05  ...   
min                         0.000000e+00                    1.900000e+01  ...   
25%                         3.412500e+02                    7.806000e+03  ...   
50%                         1.049500e+03                    1.978100e+04  ...   
75%                         5.027250e+03                    5.261900e+04  ...   
max                         4.825314e+06                    2.606664e+06  ...   

       jhu_cre_cases_deaths_single_fathers_pop  \
count                              3142.000000   
mean                               1312.223425   
std                                4140.653482   
min                                   0.000000   
25%                                 119.000000   
50%                                 331.000000   
75%                                 963.000000   
max                              119389.000000   

       jhu_cre_cases_deaths_plus_family_homes  \
count                             3142.000000   
mean                              1155.366327   
std                               9782.395332   
min    

In [134]:
## using lower quartiles, mean, upper quartile 47, 110, 261 ##

death_catlow = 47
death_catmed = 110
death_catintermed = 261
death_cathigh = 369

count = 0


for (column, columnData) in jhu_cre.iterrows():
    deaths = jhu_cre['jhu_cre_cases_deaths_deaths'].values[count]
    dc = jhu_cre['death_cat']
    if deaths <= death_catlow:
        dc.values[count] = 'low'
    elif deaths > death_catlow and deaths <= death_catmed:
        dc.values[count] = 'med'
    elif deaths > death_catmed and deaths <= death_catintermed:
        dc.values[count] = 'intermed'
    else:
        dc.values[count] = 'high'
        

    count = count + 1

In [135]:
# Assigning numerical values and storing in another column

jhu_cre['death_Cat'] = LabelEncoder().fit_transform(jhu_cre['death_cat'])

In [136]:
jhu_cre.dtypes

jhu_cre_cases_deaths_cases                      int64
jhu_cre_cases_deaths_deaths                     int64
jhu_cre_cases_deaths_popuni                     int64
jhu_cre_cases_deaths_total_population           int64
jhu_cre_cases_deaths_zero_rf                    int64
jhu_cre_cases_deaths_one_two_rf                 int64
jhu_cre_cases_deaths_three_rf                   int64
jhu_cre_cases_deaths_housing_units              int64
jhu_cre_cases_deaths_hispanic_pop               int64
jhu_cre_cases_deaths_white_pop                  int64
jhu_cre_cases_deaths_black_pop                  int64
jhu_cre_cases_deaths_native_pop                 int64
jhu_cre_cases_deaths_asian_pop                  int64
jhu_cre_cases_deaths_pacific_islander_pop       int64
jhu_cre_cases_deaths_other_race_pop             int64
jhu_cre_cases_deaths_bi_tri_racial_pop          int64
jhu_cre_cases_deaths_male_pop                   int64
jhu_cre_cases_deaths_female_pop                 int64
jhu_cre_cases_deaths_veteran

In [155]:
y = jhu_cre["jhu_cre_cases_deaths_deaths"]
X = jhu_cre.drop(columns=["jhu_cre_cases_deaths_deaths", "death_cat", "jhu_cre_cases_deaths_homeowner_vacancy", "jhu_cre_cases_deaths_asian_pop"], axis=1)

In [156]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=50)

In [157]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [158]:
scaler.fit(X_train)

StandardScaler()

In [159]:
X_train = scaler.transform(X_train)

In [160]:
X_test = scaler.transform(X_test)

In [161]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)

In [162]:
pca.fit(X_train)

PCA(n_components=2)

In [163]:
#Apply transformation on both train and test set
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [164]:
var = pca.explained_variance_ratio_
var.sum()

0.8588569090241316

In [165]:
# Storing methods as variables for formatting
cr = classification_report
ar = accuracy_score
cm = confusion_matrix

In [166]:
from sklearn.linear_model import LogisticRegression

LRM = LogisticRegression()
LRM.fit(X_train,y_train)
predLRM = LRM.predict(X_test)

print(f"the accuracy score is:{ar(y_test,predLRM)}")

print(f"confusion matrix:\n{cm(y_test,predLRM)}")

the accuracy score is:0.01653944020356234
confusion matrix:
[[4 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [92]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=1000,
   random_state=1)

In [93]:
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'high'

In [94]:
y_pred = classifier.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.013994910941475827
